name: Create C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.5'

    - name: Create C# Project
      run: |
        dotnet new console -o ImprovedPublicTransport
        cd ImprovedPublicTransport
        dotnet build
